server:
  port: 8081

spring:
  application:
    name: order-service


#  datasource:
#    url: jdbc:postgresql://order-db:5432/order_db
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: full

  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  jmx:
    enabled: false
eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:8761/eureka
       defaultZone: http://localhost:8761/eureka

