server:
  port: 8090

spring:
  application:
    name: driver-service
  
  datasource:
    url: jdbc:postgresql://driver-db:5432/driver_db
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com.example.driverservice: DEBUG

# Driver service specific configurations
driver:
  performance:
    rating-weight: 0.3
    delivery-weight: 0.4
    time-weight: 0.3
  availability:
    max-active-deliveries: 3
    min-rest-hours: 8